import type { Metadata } from "next";
import { Montserrat, IBM_Plex_Sans_Thai } from "next/font/google";
import "./globals.css";
import Sidemenu from "@/components/Sidemenu";
import Topmenu from "@/components/Topmenu";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  display: "swap",
});

const ibmPlexSans = IBM_Plex_Sans_Thai({
  variable: "--font-ibm-plex-sans-thai",
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["thai"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${montserrat.variable} ${ibmPlexSans.variable} antialiased`}
      >
        <div className="flex h-screen">
          <Sidemenu />
          <div className="flex-1 relative">
            <Topmenu />
            <main className="overflow-hidden">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}
